"""added table-wise permission and relation between db's corrected relartionship

Revision ID: 05856656c854
Revises: a589188716d4
Create Date: 2025-04-17 09:58:11.241753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05856656c854'
down_revision: Union[str, None] = 'a589188716d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('connection_table_name_connection_id_fkey', 'connection_table_name', type_='foreignkey')
    op.create_foreign_key(None, 'connection_table_name', 'database_connection', ['connection_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('related_database_connection_id_fkey', 'related_database', type_='foreignkey')
    op.drop_constraint('related_database_related_connection_id_fkey', 'related_database', type_='foreignkey')
    op.create_foreign_key(None, 'related_database', 'database_connection', ['connection_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'related_database', 'database_connection', ['related_connection_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('role_table_name_role_id_fkey', 'role_table_name', type_='foreignkey')
    op.drop_constraint('role_table_name_table_name_id_fkey', 'role_table_name', type_='foreignkey')
    op.create_foreign_key(None, 'role_table_name', 'connection_table_name', ['table_name_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_table_name', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_column('role_table_name', 'table_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_table_name', sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'role_table_name', type_='foreignkey')
    op.drop_constraint(None, 'role_table_name', type_='foreignkey')
    op.create_foreign_key('role_table_name_table_name_id_fkey', 'role_table_name', 'connection_table_name', ['table_name_id'], ['id'])
    op.create_foreign_key('role_table_name_role_id_fkey', 'role_table_name', 'role', ['role_id'], ['id'])
    op.drop_constraint(None, 'related_database', type_='foreignkey')
    op.drop_constraint(None, 'related_database', type_='foreignkey')
    op.create_foreign_key('related_database_related_connection_id_fkey', 'related_database', 'database_connection', ['related_connection_id'], ['id'])
    op.create_foreign_key('related_database_connection_id_fkey', 'related_database', 'database_connection', ['connection_id'], ['id'])
    op.drop_constraint(None, 'connection_table_name', type_='foreignkey')
    op.create_foreign_key('connection_table_name_connection_id_fkey', 'connection_table_name', 'database_connection', ['connection_id'], ['id'])
    # ### end Alembic commands ###
