"""updated chartAccess

Revision ID: 1259f2a13aa5
Revises: d9f2b6d81f89
Create Date: 2025-04-22 15:17:45.294512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1259f2a13aa5'
down_revision: Union[str, None] = 'd9f2b6d81f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart_access_request', sa.Column('title', sa.String(), nullable=False))
    op.add_column('chart_access_request', sa.Column('query', sa.Text(), nullable=False))
    op.add_column('chart_access_request', sa.Column('report', sa.Text(), nullable=True))
    op.add_column('chart_access_request', sa.Column('type', sa.String(), nullable=False))
    op.add_column('chart_access_request', sa.Column('relevance', sa.Double(), nullable=False))
    op.add_column('chart_access_request', sa.Column('is_time_based', sa.Boolean(), nullable=True))
    op.add_column('chart_access_request', sa.Column('chart_type', sa.String(), nullable=False))
    op.add_column('chart_access_request', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('chart_access_request', sa.Column('is_user_generated', sa.Boolean(), nullable=False))
    op.add_column('chart_access_request', sa.Column('created_by', sa.UUID(), nullable=False))
    op.drop_constraint('chart_access_request_chart_id_fkey', 'chart_access_request', type_='foreignkey')
    op.create_foreign_key(None, 'chart_access_request', 'user', ['created_by'], ['id'])
    op.drop_column('chart_access_request', 'chart_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart_access_request', sa.Column('chart_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chart_access_request', type_='foreignkey')
    op.create_foreign_key('chart_access_request_chart_id_fkey', 'chart_access_request', 'chart', ['chart_id'], ['id'])
    op.drop_column('chart_access_request', 'created_by')
    op.drop_column('chart_access_request', 'is_user_generated')
    op.drop_column('chart_access_request', 'created_at')
    op.drop_column('chart_access_request', 'chart_type')
    op.drop_column('chart_access_request', 'is_time_based')
    op.drop_column('chart_access_request', 'relevance')
    op.drop_column('chart_access_request', 'type')
    op.drop_column('chart_access_request', 'report')
    op.drop_column('chart_access_request', 'query')
    op.drop_column('chart_access_request', 'title')
    # ### end Alembic commands ###
