"""Added metrics table

Revision ID: 133d365815ab
Revises: 9f7f8702d7bc
Create Date: 2025-04-28 17:43:49.896985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '133d365815ab'
down_revision: Union[str, None] = '9f7f8702d7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_response_time_id', table_name='response_time')
    op.drop_index('ix_response_time_url', table_name='response_time')
    op.drop_table('response_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_time',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('process_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='response_time_pkey')
    )
    op.create_index('ix_response_time_url', 'response_time', ['url'], unique=False)
    op.create_index('ix_response_time_id', 'response_time', ['id'], unique=False)
    # ### end Alembic commands ###
