"""updated chartAccess

Revision ID: 4871642900f9
Revises: 12243607f775
Create Date: 2025-04-23 10:56:39.333459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4871642900f9'
down_revision: Union[str, None] = '12243607f775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart_access_request', sa.Column('project_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'chart_access_request', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chart_access_request', type_='foreignkey')
    op.drop_column('chart_access_request', 'project_id')
    # ### end Alembic commands ###
