"""Added datasource connection to chart-access-request models

Revision ID: 610ebb8a2649
Revises: ba06dc4dcbf4
Create Date: 2025-05-06 13:45:57.459972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610ebb8a2649'
down_revision: Union[str, None] = 'ba06dc4dcbf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart_access_request', sa.Column('database_connection_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'chart_access_request', 'database_connection', ['database_connection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chart_access_request', type_='foreignkey')
    op.drop_column('chart_access_request', 'database_connection_id')
    # ### end Alembic commands ###
