"""Added is_super, is_owner, is_global with default

Revision ID: 7aba2a900c97
Revises: merge_dashboard_id_changes
Create Date: 2025-04-10 16:45:04.604061
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aba2a900c97'
down_revision: Union[str, None] = 'merge_dashboard_id_changes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('api_key_user_id_fkey', 'api_key', type_='foreignkey')
    op.drop_constraint('api_key_project_id_fkey', 'api_key', type_='foreignkey')
    op.create_foreign_key(None, 'api_key', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'api_key', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # Add columns with default values to avoid NOT NULL constraint violations.
    # This migration can run on DBs where some columns already exist.
    inspector = sa.inspect(op.get_bind())

    role_cols = {col["name"] for col in inspector.get_columns("role")}
    user_cols = {col["name"] for col in inspector.get_columns("user")}
    user_dashboard_cols = {col["name"] for col in inspector.get_columns("user_dashboard")}
    user_project_role_cols = {col["name"] for col in inspector.get_columns("user_project_role")}

    added_role_is_global = False
    added_user_is_super = False
    added_user_dashboard_is_owner = False
    added_user_project_role_is_owner = False

    if "is_global" not in role_cols:
        op.add_column('role', sa.Column('is_global', sa.Boolean(), nullable=False, server_default=sa.false()))
        added_role_is_global = True
    if "is_super" not in user_cols:
        op.add_column('user', sa.Column('is_super', sa.Boolean(), nullable=False, server_default=sa.false()))
        added_user_is_super = True
    if "is_owner" not in user_dashboard_cols:
        op.add_column('user_dashboard', sa.Column('is_owner', sa.Boolean(), nullable=False, server_default=sa.false()))
        added_user_dashboard_is_owner = True
    if "is_owner" not in user_project_role_cols:
        op.add_column('user_project_role', sa.Column('is_owner', sa.Boolean(), nullable=False, server_default=sa.false()))
        added_user_project_role_is_owner = True

    # Remove server defaults only for newly added columns
    if added_role_is_global:
        op.alter_column('role', 'is_global', server_default=None)
    if added_user_is_super:
        op.alter_column('user', 'is_super', server_default=None)
    if added_user_dashboard_is_owner:
        op.alter_column('user_dashboard', 'is_owner', server_default=None)
    if added_user_project_role_is_owner:
        op.alter_column('user_project_role', 'is_owner', server_default=None)

    op.drop_constraint('user_chart_user_id_fkey', 'user_chart', type_='foreignkey')
    op.drop_constraint('user_chart_chart_id_fkey', 'user_chart', type_='foreignkey')
    op.create_foreign_key(None, 'user_chart', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_chart', 'chart', ['chart_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('user_dashboard_dashboard_id_fkey', 'user_dashboard', type_='foreignkey')
    op.drop_constraint('user_dashboard_user_id_fkey', 'user_dashboard', type_='foreignkey')
    op.create_foreign_key(None, 'user_dashboard', 'dashboard', ['dashboard_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_dashboard', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_project_role', 'is_owner')

    op.drop_constraint(None, 'user_dashboard', type_='foreignkey')
    op.drop_constraint(None, 'user_dashboard', type_='foreignkey')
    op.create_foreign_key('user_dashboard_user_id_fkey', 'user_dashboard', 'user', ['user_id'], ['id'])
    op.create_foreign_key('user_dashboard_dashboard_id_fkey', 'user_dashboard', 'dashboard', ['dashboard_id'], ['id'])

    op.drop_column('user_dashboard', 'is_owner')

    op.drop_constraint(None, 'user_chart', type_='foreignkey')
    op.drop_constraint(None, 'user_chart', type_='foreignkey')
    op.create_foreign_key('user_chart_chart_id_fkey', 'user_chart', 'chart', ['chart_id'], ['id'])
    op.create_foreign_key('user_chart_user_id_fkey', 'user_chart', 'user', ['user_id'], ['id'])

    op.drop_column('user', 'is_super')
    op.drop_column('role', 'is_global')

    op.drop_constraint(None, 'api_key', type_='foreignkey')
    op.drop_constraint(None, 'api_key', type_='foreignkey')
    op.create_foreign_key('api_key_project_id_fkey', 'api_key', 'project', ['project_id'], ['id'])
    op.create_foreign_key('api_key_user_id_fkey', 'api_key', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
