"""note schema changes

Revision ID: 959b886b0d31
Revises: 0e0c8a0227b7
Create Date: 2025-11-24 15:37:32.462004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959b886b0d31'
down_revision: Union[str, None] = '0e0c8a0227b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(table: str, column: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return any(col["name"] == column for col in inspector.get_columns(table))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('executive_summary', sa.String(), nullable=False),
    sa.Column('key_metrics', sa.String(), nullable=False),
    sa.Column('insights_and_patterns', sa.String(), nullable=False),
    sa.Column('recommendations', sa.String(), nullable=False),
    sa.Column('areas_of_concern', sa.String(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    if _has_column('database_connection', 'db_description'):
        op.drop_column('database_connection', 'db_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database_connection', sa.Column('db_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('business_insights')
    # ### end Alembic commands ###
