"""added is_favorite to userdashboard and user charts

Revision ID: 976a1c8144cf
Revises: e0a15e3dcacf
Create Date: 2025-04-15 13:55:56.278554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976a1c8144cf'
down_revision: Union[str, None] = 'e0a15e3dcacf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chart', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.add_column('user_dashboard', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_dashboard', 'is_favorite')
    op.drop_column('user_chart', 'is_favorite')
    # ### end Alembic commands ###
