"""Added metrics table

Revision ID: 9f7f8702d7bc
Revises: 4871642900f9
Create Date: 2025-04-28 17:12:19.474373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f7f8702d7bc'
down_revision: Union[str, None] = '4871642900f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_request_times_id', table_name='request_times')
    op.drop_index('ix_request_times_url', table_name='request_times')
    op.drop_table('request_times')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_times',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('process_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='request_times_pkey')
    )
    op.create_index('ix_request_times_url', 'request_times', ['url'], unique=False)
    op.create_index('ix_request_times_id', 'request_times', ['id'], unique=False)
    # ### end Alembic commands ###
