"""Add KPI info and chart status columns

Revision ID: b3d4c2e8f1a2
Revises: f8c9a3b4e2d1
Create Date: 2025-11-10 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d4c2e8f1a2'
down_revision: Union[str, None] = 'f8c9a3b4e2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('kpi_info', sa.String(), nullable=True))
    op.add_column('project', sa.Column('prod_desc', sa.String(), nullable=True))
    op.add_column('dashboard', sa.Column('kpi_info', sa.String(), nullable=True))

    chart_status_enum = sa.Enum('draft', 'published', name='chart_status')
    chart_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'chart',
        sa.Column(
            'status',
            chart_status_enum,
            nullable=False,
            server_default=sa.text("'draft'::chart_status"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chart', 'status')
    chart_status_enum = sa.Enum('draft', 'published', name='chart_status')
    chart_status_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_column('dashboard', 'kpi_info')
    op.drop_column('project', 'prod_desc')
    op.drop_column('project', 'kpi_info')
    # ### end Alembic commands ###

