"""Added datasource connection to userChart models

Revision ID: ba06dc4dcbf4
Revises: 133d365815ab
Create Date: 2025-05-06 13:38:19.126724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba06dc4dcbf4'
down_revision: Union[str, None] = '133d365815ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chart', sa.Column('database_connection_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'user_chart', 'database_connection', ['database_connection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_chart', type_='foreignkey')
    op.drop_column('user_chart', 'database_connection_id')
    # ### end Alembic commands ###
