"""Added minor changes

Revision ID: be169106faaa
Revises: 9404d35142aa
Create Date: 2025-04-08 13:04:23.644356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be169106faaa'
down_revision: Union[str, None] = '9404d35142aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_permission')
    op.drop_table('dashboard_permission')
    op.drop_table('chart_permission')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_permission',
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chart_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['chart.id'], name='chart_permission_chart_id_fkey'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name='chart_permission_permission_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='chart_permission_role_id_fkey'),
    sa.PrimaryKeyConstraint('role_id', 'chart_id', 'permission_id', name='chart_permission_pkey')
    )
    op.create_table('dashboard_permission',
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dashboard_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboard.id'], name='dashboard_permission_dashboard_id_fkey'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name='dashboard_permission_permission_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='dashboard_permission_role_id_fkey'),
    sa.PrimaryKeyConstraint('role_id', 'dashboard_id', 'permission_id', name='dashboard_permission_pkey')
    )
    op.create_table('project_permission',
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name='project_permission_permission_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='project_permission_project_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='project_permission_role_id_fkey'),
    sa.PrimaryKeyConstraint('role_id', 'project_id', 'permission_id', name='project_permission_pkey')
    )
    # ### end Alembic commands ###
