"""added summarised_desc column in project table

Revision ID: cd06cabc976c
Revises: 959b886b0d31
Create Date: 2025-11-24 15:44:59.301168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd06cabc976c'
down_revision: Union[str, None] = '959b886b0d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('summarised_desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'summarised_desc')
    # ### end Alembic commands ###
