"""Added consent given field in database connection

Revision ID: d49e851a5914
Revises: 05856656c854
Create Date: 2025-04-17 11:24:29.441009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd49e851a5914'
down_revision: Union[str, None] = '05856656c854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database_connection', sa.Column('consent_given', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('database_connection', 'consent_given')
    # ### end Alembic commands ###
