"""Added db_type

Revision ID: d8dd80ba8de1
Revises: be169106faaa
Create Date: 2025-04-08 15:33:32.789770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8dd80ba8de1'
down_revision: Union[str, None] = 'be169106faaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database_connection', sa.Column('db_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('database_connection', 'db_type')
    # ### end Alembic commands ###
