"""updated the chartModel

Revision ID: d9f2b6d81f89
Revises: 59b551104fd9
Create Date: 2025-04-22 14:57:19.770862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f2b6d81f89'
down_revision: Union[str, None] = '59b551104fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chart', 'is_time_based',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chart', 'is_time_based',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
