"""Added is_super, is_owner and made it nullable

Revision ID: e0a15e3dcacf
Revises: 7aba2a900c97
Create Date: 2025-04-10 16:54:08.251889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0a15e3dcacf'
down_revision: Union[str, None] = '7aba2a900c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'is_global',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'is_super',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_dashboard', 'is_owner',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_project_role', 'is_owner',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_project_role', 'is_owner',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_dashboard', 'is_owner',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_super',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('role', 'is_global',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
