"""Added datasource connection to DashboardCharts models

Revision ID: e4eb7059742c
Revises: 610ebb8a2649
Create Date: 2025-05-06 15:14:51.938046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4eb7059742c'
down_revision: Union[str, None] = '610ebb8a2649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_chart', sa.Column('database_connection_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'dashboard_chart', 'database_connection', ['database_connection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dashboard_chart', type_='foreignkey')
    op.drop_column('dashboard_chart', 'database_connection_id')
    # ### end Alembic commands ###
