"""Added status and last_checked to database_connection

Revision ID: f8c9a3b4e2d1
Revises: d49e851a5914
Create Date: 2025-11-05 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c9a3b4e2d1'
down_revision: Union[str, None] = 'd49e851a5914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database_connection', sa.Column('status', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('database_connection', sa.Column('last_checked', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('database_connection', 'last_checked')
    op.drop_column('database_connection', 'status')
    # ### end Alembic commands ###

