from sqlalchemy.orm import declarative_base

Base = declarative_base()

from app.models.schema_models import DashboardChartsModel,DashboardModel,ChartModel,ChartPermissionModel,PermissionModel,ProjectModel,ProjectPermissionModel,ApiKeyModel,UserModel,UserProjectRoleModel,DashboardPermissionModel,RoleModelc